export default {

    "lines": 
    [   {"id": 1, "name": "Los Angeles Red Line", "color": "#ff0000"},
        {"id": 2, "name": "Los Angeles Expo Line", "color": "#66ccff"},
        {"id": 3, "name": "Los Angeles Blue Line", "color": "#0033cc"},
        {"id": 4, "name": "Los Angeles Gold Line", "color": "##ffff00"},
        {"id": 5, "name": "Los Angeles Purple Line", "color": "#3333cc"},
    ],

    "members": 
    [   {"id": 1, "name": "Bob", "email": "bob@gmail.com", "password": "password", "line": 1},
        {"id": 2, "name": "Fred", "email": "fred@gmail.com", "password": "password", "line": 1},
        {"id": 3, "name": "Stan", "email": "stan@gmail.com", "password": "password", "line": 1},
        {"id": 4, "name": "Sally", "email": "sally@gmail.com", "password": "password", "line": 1},
        {"id": 5, "name": "Deb", "email": "deb@gmail.com", "password": "password", "line": 1},
        {"id": 6, "name": "Mary", "email": "mary@gmail.com", "password": "password", "line": 1},
        {"id": 7, "name": "John Doe", "email": "email@gmail.com", "password": "password", "line": 1},
    ],

    "stations": 
    [   {"id": 101, "name": "North Hollywood", "line": 1},
        {"id": 102, "name": "Universal City/Studio City", "line": 1},
        {"id": 103, "name": "Hollywood/Highland", "line": 1},
        {"id": 104, "name": "Hollywood/Vine", "line": 1},
        {"id": 105, "name": "Hollywood/Western", "line": 1},
        {"id": 106, "name": "Vermont/Sunset", "line": 1},
        {"id": 107, "name": "Vermont/Santa Monica", "line": 1},
        {"id": 108, "name": "Vermont/Beverly", "line": 1},
        {"id": 109, "name": "Wilshire/Vermont", "line": 1},
        {"id": 110, "name": "Westlake/MacArthur Park", "line": 1},
        {"id": 111, "name": "7th St/Metro Center", "line": 1},
        {"id": 112, "name": "Pershing Square", "line": 1},
        {"id": 113, "name": "Civic Center/Grand Park", "line": 1},
        {"id": 114, "name": "Union Station", "line": 1}, 

        {"id": 115, "name": "7th St/Metro Center", "line": 2}, 
        {"id": 116, "name": "Pico", "line": 2}, 
        {"id": 117, "name": "LATTC/Ortho Institute", "line": 2}, 
        {"id": 118, "name": "Jefferson/USC", "line": 2}, 
        {"id": 118, "name": "Expo Park/USC", "line": 2}, 
        {"id": 119, "name": "Expo/Vermont", "line": 2}, 
        {"id": 120, "name": "Expo/Western", "line": 2}, 
        {"id": 121, "name": "Expo/Crenshaw", "line": 2},
        {"id": 122, "name": "Farmdale", "line": 2},
        {"id": 123, "name": "Expo/La Brea", "line": 2},
        {"id": 124, "name": "La Cienega/Jefferson", "line": 2},
        {"id": 125, "name": "Culver City", "line": 2}, 
        {"id": 126, "name": "Palms", "line": 2},
        {"id": 127, "name": "Westwood/Rancho", "line": 2},
        {"id": 128, "name": "Expo/Sepulveda", "line": 2},
        {"id": 129, "name": "Expo/Bundy", "line": 2},
        {"id": 130, "name": "26th St/Bergamot", "line": 2}, 
        {"id": 131, "name": "17th St/SMC", "line": 2}, 
        {"id": 132, "name": "Downtown Santa Monica", "line": 2}, 

        {"id": 133, "name": "7th St/Metro Center", "line": 3}, 
        {"id": 134, "name": "Pico", "line": 3}, 
        {"id": 135, "name": "Grand/LATTC", "line": 3}, 
        {"id": 136, "name": "San Pedro St", "line": 3}, 
        {"id": 137, "name": "Washington", "line": 3}, 
        {"id": 138, "name": "Vernon", "line": 3}, 
        {"id": 139, "name": "Slauson", "line": 3}, 
        {"id": 140, "name": "Florence", "line": 3},
        {"id": 141, "name": "Firestone", "line": 3},
        {"id": 142, "name": "103rd St/Watts Towers", "line": 3},
        {"id": 143, "name": "Willowbrook/Rosa Parks", "line": 3},
        {"id": 144, "name": "Compton", "line": 3}, 
        {"id": 145, "name": "Artesia", "line": 3},
        {"id": 146, "name": "Del Amo", "line": 3},
        {"id": 147, "name": "Wardlow", "line": 3},
        {"id": 148, "name": "Willow St", "line": 3},
        {"id": 149, "name": "Pacific Coast Highway", "line": 3}, 
        {"id": 150, "name": "Anaheim St", "line": 3}, 
        {"id": 151, "name": "5th Street", "line": 3}, 
        {"id": 152, "name": "1st Street", "line": 3},
        {"id": 153, "name": "Downtown Long Beach", "line": 3},
        {"id": 154, "name": "Pacific Av", "line": 3},

        {"id": 155, "name": "APU/Citrus", "line": 4},
        {"id": 156, "name": "Azusa Downtown", "line": 4},
        {"id": 157, "name": "Irwindale", "line": 4},
        {"id": 158, "name": "Duarte/City of Hope", "line": 4},
        {"id": 159, "name": "Monrovia", "line": 4},
        {"id": 160, "name": "Arcadia", "line": 4},
        {"id": 161, "name": "Sierra Madre Villa", "line": 4},
        {"id": 162, "name": "Allen", "line": 4},
        {"id": 163, "name": "Lake Avenue", "line": 4},
        {"id": 164, "name": "Memorial Park", "line": 4},
        {"id": 165, "name": "Del Mar", "line": 4},
        {"id": 166, "name": "Fillmore", "line": 4},
        {"id": 167, "name": "South Pasadena", "line": 4},
        {"id": 168, "name": "Highland Park", "line": 4},
        {"id": 169, "name": "Southwest Museum", "line": 4},
        {"id": 170, "name": "Heritage Square", "line": 4},
        {"id": 171, "name": "Lincoln/Cypress", "line": 4},
        {"id": 172, "name": "Chinatown", "line": 4},
        {"id": 173, "name": "Union Station", "line": 4},
        {"id": 174, "name": "Little Tokyo/Arts District", "line": 4},
        {"id": 175, "name": "Pico/Aliso", "line": 4},
        {"id": 176, "name": "Mariachi Plaza", "line": 4},
        {"id": 177, "name": "Soto", "line": 4},
        {"id": 178, "name": "Indiana", "line": 4},
        {"id": 179, "name": "Maraville", "line": 4},
        {"id": 180, "name": "East LA Civic Center", "line": 4},
        {"id": 181, "name": "Atlantic", "line": 4},

        {"id": 182, "name": "Wilshire/Western", "line": 5},
        {"id": 183, "name": "Wilshire/Normandie", "line": 5},
        {"id": 184, "name": "Wilshire/Vermont", "line": 5},
        {"id": 185, "name": "Westlake/MacArthur Park", "line": 5},
        {"id": 186, "name": "7th St/Metro Center", "line": 5},
        {"id": 187, "name": "Pershing Square", "line": 5},
        {"id": 188, "name": "Civic Center", "line": 5},
        {"id": 189, "name": "Union Station", "line": 5},

        
    ],

   

    "reports": 
    [   
        // {"id": 1, "name": "Construction", "date": "2020-11-01 12:00:00", "station": 1, strikes: 0},
        // {"id": 2, "name": "Broken Escalator", "date": "2020-11-01 12:00:00", "station": 2, strikes: 0},
        // {"id": 3, "name": "Broken Elevator", "date": "2020-11-01 12:00:00", "station": 3, strikes: 0},
        // {"id": 4, "name": "Fair Checkpoint", "date": "2020-11-01 12:00:00", "station": 4, strikes: 0}
    ],

}