export default {

    "lines": 
    [   {"id": 1, "name": "Los Angeles Red Line", "color": "#ff0000"},
        {"id": 2, "name": "Los Angeles Expo Line", "color": "#66ccff"},
        {"id": 3, "name": "Los Angeles Blue Line", "color": "#0033cc"},
        {"id": 4, "name": "Los Angeles Gold Line", "color": "##ffff00"},
        {"id": 5, "name": "Los Angeles Purple Line", "color": "#3333cc"},
    ],

    "members": 
    [   {"id": 1, "name": "Bob", "email": "bob@gmail.com", "password": "password", "line": 1},
        {"id": 2, "name": "Fred", "email": "fred@gmail.com", "password": "password", "line": 1},
        {"id": 3, "name": "Stan", "email": "stan@gmail.com", "password": "password", "line": 1},
        {"id": 4, "name": "Sally", "email": "sally@gmail.com", "password": "password", "line": 1},
        {"id": 5, "name": "Deb", "email": "deb@gmail.com", "password": "password", "line": 1},
        {"id": 6, "name": "Mary", "email": "mary@gmail.com", "password": "password", "line": 1},
        {"id": 7, "name": "John Doe", "email": "email@gmail.com", "password": "password", "line": 1},
    ],

    "stations": 
    [   {"id": 1, "name": "North Hollywood", "line": 1},
        {"id": 2, "name": "Universal City/Studio City", "line": 1},
        {"id": 3, "name": "Hollywood/Highland", "line": 1},
        {"id": 4, "name": "Hollywood/Vine", "line": 1},
        {"id": 5, "name": "Hollywood/Western", "line": 1},
        {"id": 6, "name": "Vermont/Sunset", "line": 1},
        {"id": 7, "name": "Vermont/Santa Monica", "line": 1},
        {"id": 8, "name": "Vermont/Beverly", "line": 1},
        {"id": 9, "name": "Wilshire/Vermont", "line": 1},
        {"id": 10, "name": "Westlake/MacArthur Park", "line": 1},
        {"id": 11, "name": "7th St/Metro Center", "line": 1},
        {"id": 12, "name": "Pershing Square", "line": 1},
        {"id": 13, "name": "Civic Center/Grand Park", "line": 1},
        {"id": 14, "name": "Union Station", "line": 1}, 

        {"id": 15, "name": "7th St/Metro Center", "line": 2}, 
        {"id": 16, "name": "Pico", "line": 2}, 
        {"id": 17, "name": "LATTC/Ortho Institute", "line": 2}, 
        {"id": 18, "name": "Jefferson/USC", "line": 2}, 
        {"id": 18, "name": "Expo Park/USC", "line": 2}, 
        {"id": 19, "name": "Expo/Vermont", "line": 2}, 
        {"id": 20, "name": "Expo/Western", "line": 2}, 
        {"id": 21, "name": "Expo/Crenshaw", "line": 2},
        {"id": 22, "name": "Farmdale", "line": 2},
        {"id": 23, "name": "Expo/La Brea", "line": 2},
        {"id": 24, "name": "La Cienega/Jefferson", "line": 2},
        {"id": 25, "name": "Culver City", "line": 2}, 
        {"id": 26, "name": "Palms", "line": 2},
        {"id": 27, "name": "Westwood/Rancho", "line": 2},
        {"id": 28, "name": "Expo/Sepulveda", "line": 2},
        {"id": 29, "name": "Expo/Bundy", "line": 2},
        {"id": 30, "name": "26th St/Bergamot", "line": 2}, 
        {"id": 31, "name": "17th St/SMC", "line": 2}, 
        {"id": 32, "name": "Downtown Santa Monica", "line": 2}, 

        {"id": 33, "name": "7th St/Metro Center", "line": 3}, 
        {"id": 34, "name": "Pico", "line": 3}, 
        {"id": 35, "name": "Grand/LATTC", "line": 3}, 
        {"id": 36, "name": "San Pedro St", "line": 3}, 
        {"id": 37, "name": "Washington", "line": 3}, 
        {"id": 38, "name": "Vernon", "line": 3}, 
        {"id": 39, "name": "Slauson", "line": 3}, 
        {"id": 40, "name": "Florence", "line": 3},
        {"id": 41, "name": "Firestone", "line": 3},
        {"id": 42, "name": "103rd St/Watts Towers", "line": 3},
        {"id": 43, "name": "Willowbrook/Rosa Parks", "line": 3},
        {"id": 44, "name": "Compton", "line": 3}, 
        {"id": 45, "name": "Artesia", "line": 3},
        {"id": 46, "name": "Del Amo", "line": 3},
        {"id": 47, "name": "Wardlow", "line": 3},
        {"id": 48, "name": "Willow St", "line": 3},
        {"id": 49, "name": "Pacific Coast Highway", "line": 3}, 
        {"id": 50, "name": "Anaheim St", "line": 3}, 
        {"id": 51, "name": "5th Street", "line": 3}, 
        {"id": 52, "name": "1st Street", "line": 3},
        {"id": 53, "name": "Downtown Long Beach", "line": 3},
        {"id": 54, "name": "Pacific Av", "line": 3},

        {"id": 55, "name": "APU/Citrus", "line": 4},
        {"id": 56, "name": "Azusa Downtown", "line": 4},
        {"id": 57, "name": "Irwindale", "line": 4},
        {"id": 58, "name": "Duarte/City of Hope", "line": 4},
        {"id": 59, "name": "Monrovia", "line": 4},
        {"id": 60, "name": "Arcadia", "line": 4},
        {"id": 61, "name": "Sierra Madre Villa", "line": 4},
        {"id": 62, "name": "Allen", "line": 4},
        {"id": 63, "name": "Lake Avenue", "line": 4},
        {"id": 64, "name": "Memorial Park", "line": 4},
        {"id": 65, "name": "Del Mar", "line": 4},
        {"id": 66, "name": "Fillmore", "line": 4},
        {"id": 67, "name": "South Pasadena", "line": 4},
        {"id": 68, "name": "Highland Park", "line": 4},
        {"id": 69, "name": "Southwest Museum", "line": 4},
        {"id": 70, "name": "Heritage Square", "line": 4},
        {"id": 71, "name": "Lincoln/Cypress", "line": 4},
        {"id": 72, "name": "Chinatown", "line": 4},
        {"id": 73, "name": "Union Station", "line": 4},
        {"id": 74, "name": "Little Tokyo/Arts District", "line": 4},
        {"id": 75, "name": "Pico/Aliso", "line": 4},
        {"id": 76, "name": "Mariachi Plaza", "line": 4},
        {"id": 77, "name": "Soto", "line": 4},
        {"id": 78, "name": "Indiana", "line": 4},
        {"id": 79, "name": "Maraville", "line": 4},
        {"id": 80, "name": "East LA Civic Center", "line": 4},
        {"id": 81, "name": "Atlantic", "line": 4},

        {"id": 82, "name": "Wilshire/Western", "line": 5},
        {"id": 83, "name": "Wilshire/Normandie", "line": 5},
        {"id": 84, "name": "Wilshire/Vermont", "line": 5},
        {"id": 85, "name": "Westlake/MacArthur Park", "line": 5},
        {"id": 86, "name": "7th St/Metro Center", "line": 5},
        {"id": 87, "name": "Pershing Square", "line": 5},
        {"id": 88, "name": "Civic Center", "line": 5},
        {"id": 89, "name": "Union Station", "line": 5},

        
    ],

   

    "reports": 
    [   
        // {"id": 1, "name": "Construction", "date": "2020-11-01 12:00:00", "station": 1, strikes: 0},
        // {"id": 2, "name": "Broken Escalator", "date": "2020-11-01 12:00:00", "station": 2, strikes: 0},
        // {"id": 3, "name": "Broken Elevator", "date": "2020-11-01 12:00:00", "station": 3, strikes: 0},
        // {"id": 4, "name": "Fair Checkpoint", "date": "2020-11-01 12:00:00", "station": 4, strikes: 0}
    ],

}